### ISSUE TITLE
Table: Is controlling pagination externally possible?

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/hive#346]
react-table has .gotoPage on the instance, maybe this needs to be mirrored.

**Comment by danad02** [comment]
@utkukaratas So I've been experimenting with react-table to overcome this issue. It should be possible through the `useControlledState` option of the table as described here in the documentation FAQ: https://react-table.tanstack.com/docs/faq#how-can-i-manually-control-the-table-state

However, usage of that option brings other problems. In current implementation if you just passed down your own `pageIndex` it would call `onPaginationChange` callback in the `useEffect` hook. This is something you **want** in most cases, because the page actually changed and you want the `onPaginationChange` to be called. But if you want to skip the `onPaginationChange` call then the implementation becomes more complicated.
